In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("Data.csv")
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values

print (X)
print (Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


**Handling Missing values**

1.   ignore them i.e delete the whole row - useful incase of large ds
2.   replace with (mean-done freq) or (median) or (mode-useful in categorical var)

useful lib is scikitlearn-sklearn[pckg]impute[module] SimpleImputer[class]




In [3]:
from sklearn.impute import SimpleImputer
##creating obj for SimpleImputer Class
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
##fit() to find and compute the mean
imputer.fit(X[:, 1:3]) ##all rows and all numerical col in X
##transform to replace the nan by mean val
X[:, 1:3] = imputer.transform(X[:, 1:3])
print (X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


**Encoding Categorical var**
we can encode in into numeric data like 0,1,2,3.... but the computer tries to find a series of repetition in them and learn from it-- therfore to avoid it we use binary encoding like 000,001,010...called OneHotEncoding technique

in DV-Y like Yes or No categ we can use 0/1

1.   IV-X : compose module in sklearn package - ColumnTransformer class &
preprocessing module -  OneHotEncoder class

need to convert it into numpy array coz fit_transform() doesn't give a numpy array o/p
2. DV-Y : we use LabelEncoder class
noneed to convert it into a numpy array class. 



In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
##creating object for ColumnTransfer class
## transformers argument = 3 things to be specified - method, name of method, column you want to apply the method
##here the method = encoder, name = onehotencoder(), column = 0th
##remainder we give a code word like 'passthrough'
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
##we have fit_transform() function --> but it doesnt return a numpy array so we use np.array() and convert the o/p of it.
X = ct.fit_transform(X)
print (X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [21]:
from sklearn.preprocessing import LabelEncoder
##creating object of LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
print (Y)

[0 1 0 0 1 1 0 1 0 1]


Apply **Feature Scaling** -(scaling the range of all feat to prevent dominance of one feat over another) after Splitting DS into Test and Train set  --- done after splitting to prevent *information leakage of test set before the training is done.*

splitting into X_train, X_test, Y_train, Y_test ---> returned by train_test_split() of train_test_split fn of model_selection module of scikitlearn pckg. The fn i/p are matrix of features of X, Dep var vector Y, test set split size, fix the random seed to get same split always coz train_test_split() splits the DS randomly each time.

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [14]:
print (x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [15]:
print (x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [16]:
print (y_train)

[0 1 0 0 1 1 0 1]


In [17]:
print (y_test)

[0 1]


**Feature Scaling**
done only on x_train-fit_transform and x_test-only transform(no fit coz x_train should be new data for prediction model) to get the congruent scalar.
'fit' calc the mean and std_dev, 
'transform' performs the standardization formula.

2ways -  

1.   standardization-can be done always
2.   normalization-can be done when the feature variables are normaolised values

noneed to perform Feature scaling on all X var - i.e on *dummy variables* like encoded categ var no need to apply, and on numerical var like 'age', big range numerical var like 'salary' we should apply

sklearn.preprocessing module --  StandardScaler Class

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()  ##no i/p param
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])


In [24]:
print (x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [25]:
print (x_test) 

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
